### ISSUE TITLE
Add new regions

### ISSUE THREAD

**Issue by selphiron** [simra-project/simra-ios#22]
SimRa now also supports the regions Pforzheim/Enzkreis, Augsburg and Bochum. These regions have to be selectable in the profile menu. London has to be removed from the profile menu, since we don't have any contact persons there. However, the region code 2 is still reserved for London.

The region codes:
0 = Please Choose (default value)
1 = Berlin, 2 = London, 3 = Other, 4 = Bern, 5 = Pforzheim/Enzkreis, 6 = Augsburg, 7 = Bochum

**Comment by ckrey** [comment]
Two questions:

1) Wouldn't it be a good idea to download the table from the backend at program start or on request? Otherwise we will have to change the source code and prepare a new version everytime a new region joins?
2) I do maintain an English and German version of the table (e.g. "Other"/"Anderswo") and a second table containing the "region" code for the API (e.g. "other"). Can we simplify this?

**Comment by selphiron** [comment]
1. Yes, that would be a good idea. But the last downloaded table should be saved locally, in case the user does not have a working internet connection, when the app starts. I will inform you, when the backend is ready for this.
2. That would propably a good idea. Maybe ditch the numers altogether and write the region name instead? In that case the table from the backend would just contain a list with display name (eng)=display name(ger)=api-loc name\n(break line). As of now, it would look like this:
Please Choose=Bitte auswählen=UNKNOWN,
Berlin/Potsdam=Berlin/Potsdam=Berlin,
Other=Sonstiges=other,
Bern=Bern=Bern,
Pforzheim/Enzkreis=Pforzheim/Enzkreis=Pforzheim,
Augsburg=Augsburg=Augsburg
Bochum=Bochum=Bochum

I think it would be a good idea to sort the entries alphabetically, when receiving the table. What do you think?
3. No, it is just Pforzheim. But in the dropdown menu it is shown as "Pforzheim/Enzkreis". Same is true for Berlin and "Berlin/Potsdam" btw.
