### ISSUE TITLE
Missing additional information in rides without incidents

### ISSUE THREAD

**Issue by selphiron** [simra-project/simra-ios#34]
@ckrey 
The automatically detected false positives in SimRa get deleted before the ride is uploaded (this is rather new in Android, but was the case in iOS from the beginning). But information such as phone location, bike type and wether a child or a trailer is transported with the bike is added to the incidents.
This means that we do not get the information about bike type etc. in uploaded rides where no incidents happened. This is a problem that needs to be fixed.

Suggestion: When a ride does not have a real incident, add an incident in the first "bucket" (where GPS information are present). The type of the incident is "0" and the description is "3fzr". The rest is default.

This still leaves us with the problem that we have many rides without informations such as bike type in our backend. But we can fix this, since we store the information returned by the backend after each ride upload. The algorithm would loop through the rides on the phone and search for a ride without incidents. Once found, it would try to restore the information about bike type etc. by looking for older and newer rides, until it finds one newer and one older ride with incidents. If the bike type (and other) information of the newer and older ride are the same, take these information for the ride where these information were missing. Do this for each ride.

What happens, if there is no newer ride with an incident? In that case take the actual settings of bike type (etc.) and add that information to the ride.

What happens, if there is no older ride with an incident? In that case take the information of the newer ride with an incident.

Then, these rides must be uploaded again to the backend (with a different api request than usual) so that the faulty rides in the backend can be overwritten. 
But that could lead to a problem if there are many such rides. For that case, I have two solutions:
1) Do it for one ride per start of the app (find 1 ride with missing information, add information, upload ride) 
2) Do it only in wi-fi

**Comment by ckrey** [comment]
Oh, true. Retrospectively it was not a good idea to put the trip's attributes in the incidents...

Question:
- will the dummy incident be counted in statistics?
- we could simply update the rides again using fileHash/filePassword

We do not need the algorithm to determine the phone location / bike type / child seat / trailer in iOS, because the information is stored independently of the incidents internally.

I would ask the user the next time when a ride is uploaded. This ensures the user is in the environment (WIFI or not) preferred for uploading. E.g. "You have xx rides which need to be updated on the backend, would you like to transfer them now?"

**Comment by selphiron** [comment]
> will the dummy incident be counted in statistics?
No, that would break the statistics for the user.

> we could simply update the rides again using fileHash/filePassword
Yes.

We need the algorithm to determine the phone location etc. because these information could have been changed (we have quite a few users that change their ride settings frequently).

I like to ask the user. But maybe we should also show them how much MB the data are and that it can take a couple of minutes.

Oh and one more thing. We need different incident description strings for non-incidents we added later in old rides and for non-incidents we add after the update. We need to know which ride settings we guessed and which ride settings we know.
So "3fzr" for the incidents of the rides which are added after the update and "k2y1" for the incidents where we guessed the ride setting information according to the algorithm described above.

**Comment by selphiron** [comment]
Hmm on second thought, I'd rather not inform the users that some rides in the past have missing information :) So uploading the corrected rides in wi-fi would be better (or uploading one corrected ride per app start)

**Comment by ckrey** [comment]
We do not need the algorithm to determine the phone location / bike type / child seat / trailer in iOS, because the information is stored independently of the incidents internally per ride.

**Comment by selphiron** [comment]
Ah, that is not the case with Android.

**Comment by ckrey** [comment]
I did change the app as follows:

- add dummy annotation if no valid annotations exists before upload "3fzr"
- at program start, reload and add dummy annotation "k2y1" if no valid annotations are stored
- when uploading a new ride successfully, check if there are rides without incidents not re-uploaded yet and upload all of them displaying "Re-Upload xx". This may take a while, but happens only once

I see 2 problems:
- Because we do not ask the user beforehand, the user will be surprised...
- We do not store the region of rides. If rides without incidents still exist on a phone which were captured in a region different than the current one, upload will fail (HTTP 400)

**Comment by selphiron** [comment]
Do you need the dummy annotation "k2y1"? I thought that you don't have to guess the ride settings in the iOS version since each rides setting is stored locally, whether it has an incident or not.

Regarding Problem 1: This should not be a problem, if we do the re-upload only in wi-fi
Regarding Problem 2: Possible solution: When a ride is reuploaded, the backend just checks in every region folder to find that ride.

What do you think?

**Comment by ckrey** [comment]
No, "k2y1" is not necessary, I can use "3fzr" in both cases.

Problem 1: OK, will re-upload only in wi-fi
Problem 2: In order to avoid an endless loop, I will ignore negative responses (400) when re-uploading

**Comment by selphiron** [comment]
Please wait for me to prepare the backend. I need to implement a new endpoint for this.

**Comment by selphiron** [comment]
Example for a dummy incident of a new ride, which needs to be uploaded but has no incidents:
```
key,lat,lon,ts,bike,childCheckBox,trailerCheckBox,pLoc,incident,i1,i2,i3,i4,i5,i6,i7,i8,i9,scary,desc,i10
,,,,0,0,0,0,-5,0,0,0,0,0,0,0,0,0,0,,0
```
